import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Layout from '../components/Layout';
import { StateContext } from '@/context/StateContext';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BASE Gear',
  description: 'Generated by jake',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      
        <body className={inter.className}>
          <StateContext>
          <Layout>
            <Toaster />
            {children}
          </Layout>
          </StateContext>
        </body>
      
    </html>
  )
}
